version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: express-mongo-test-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=express-mongo-test
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: express-mongo-test-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: 